const state = { page: "dashboard", experiments: [], validations: [], validationSummary: null, system: null, health: null, metric: "average_latency_ms", loading: true, error: null, theme: localStorage.getItem("fintwin-theme") || "dark" };

const $ = (selector) => document.querySelector(selector);
const app = $("#app");
const number = (value, digits = 1) => value === null || value === undefined || value === "" ? "—" : Number(value).toLocaleString(undefined, { maximumFractionDigits: digits, minimumFractionDigits: digits });
const integer = (value) => value === null || value === undefined ? "—" : Number(value).toLocaleString();
const compact = (value) => value ? String(value).slice(0, 8) : "—";
const dateTime = (value) => value ? new Date(value).toLocaleString([], { dateStyle: "medium", timeStyle: "short" }) : "—";
const escapeHtml = (value) => String(value ?? "—").replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#039;", '"': "&quot;" }[character]));
const metricName = (key) => ({ average_latency_ms: "Average latency", p95_latency_ms: "P95 latency", actual_tps: "Actual throughput", host_cpu_avg_percent: "Host CPU", lock_wait_count_max: "Lock waits" }[key] || key.replaceAll("_", " "));
const metricUnit = (key) => key.includes("latency") ? "ms" : key.includes("tps") ? "TPS" : key.includes("cpu") ? "%" : "";

async function api(path, options = {}) {
  const response = await fetch(path, { headers: { "Content-Type": "application/json", ...(options.headers || {}) }, ...options });
  if (!response.ok) {
    const payload = await response.json().catch(() => ({}));
    throw new Error(payload.detail || "The requested data is unavailable.");
  }
  return response.json();
}

function statusDot(value) { return value === "connected" || value === "active" || value === "ready" ? "" : value === "offline" || value === "unavailable" ? "offline" : "pending"; }
function statusText(value) { return String(value || "unavailable").replaceAll("_", " "); }
function statusBadge(value) { const key = String(value || "").toLowerCase(); const cls = key.includes("complete") ? "complete" : key.includes("fail") || key.includes("offline") ? "failed" : key.includes("elevated") || key.includes("running") ? "elevated" : ""; return `<span class="badge ${cls}">${escapeHtml(statusText(value))}</span>`; }

function setSystemStatus() {
  const status = state.system || {};
  const entries = [["PostgreSQL", status.database], ["Telemetry", status.telemetry], ["ML models", status.ml_models]];
  $("#sidebar-status").innerHTML = `<p class="eyebrow">SYSTEM STATUS</p>${entries.map(([label, value]) => `<div class="status-row"><span class="status-dot ${statusDot(value)}"></span><span>${label}</span><b>${escapeHtml(statusText(value))}</b></div>`).join("")}`;
  const database = status.database;
  $("#top-status").innerHTML = `<i class="status-dot ${statusDot(database)}"></i>${database === "connected" ? "PostgreSQL connected" : "Database unavailable"}`;
}

function applyTheme(theme) {
  state.theme = theme === "light" ? "light" : "dark";
  document.documentElement.dataset.theme = state.theme;
  localStorage.setItem("fintwin-theme", state.theme);
  const toggle = $("#theme-toggle");
  if (toggle) {
    const light = state.theme === "light";
    toggle.setAttribute("aria-label", light ? "Switch to dark theme" : "Switch to light theme");
    toggle.title = light ? "Switch to dark theme" : "Switch to light theme";
    toggle.innerHTML = `<span class="theme-icon" aria-hidden="true">${light ? "☾" : "☼"}</span><span class="theme-label">${light ? "Dark" : "Light"}</span>`;
  }
}

function toggleTheme() { applyTheme(state.theme === "dark" ? "light" : "dark"); }

function setPage(page) {
  state.page = page;
  document.querySelectorAll(".nav-item").forEach((button) => button.classList.toggle("active", button.dataset.page === page));
  const labels = { dashboard: ["WORKSPACE", "Dashboard"], experiments: ["EXPERIMENTS", "Experiments"], prediction: ["PREDICTION", "Prediction"], whatif: ["COMPARISON", "What-If Analysis"], optimization: ["PERFORMANCE REVIEW", "Optimization"], validation: ["VALIDATION", "Validation"] };
  $("#page-kicker").textContent = labels[page][0]; $("#page-title").textContent = labels[page][1];
  render(); window.scrollTo({ top: 0, behavior: "smooth" });
}

function skeleton() { app.innerHTML = `<div class="page-hero"><div><div class="skeleton" style="width:260px;min-height:37px"></div><div class="skeleton" style="width:480px;min-height:16px;margin-top:12px"></div></div></div><div class="kpi-grid">${Array.from({ length: 5 }, () => '<div class="skeleton"></div>').join("")}</div><div class="skeleton" style="min-height:300px"></div>`; }
function errorState(title, message) { return `<div class="error-state"><div><b>${escapeHtml(title)}</b><span>${escapeHtml(message)}</span></div></div>`; }
function emptyState(title, description) { return `<div class="empty-state"><div><b>${escapeHtml(title)}</b><span>${escapeHtml(description)}</span></div></div>`; }
function cardHead(title, text, action = "") { return `<div class="section-head"><div><h3>${title}</h3><p>${text || ""}</p></div>${action}</div>`; }
function pageHero(title, description, action = "") { return `<div class="page-hero"><div><h2>${title}</h2><p>${description}</p></div>${action}</div>`; }
function latestExperiment() { return state.experiments.find((experiment) => experiment.status === "COMPLETED") || state.experiments[0]; }
function latestValidation() { return state.validations.find((validation) => validation.validation_status === "COMPLETED"); }

function kpi(label, value, unit, note) { return `<article class="card kpi"><span class="kpi-label">${label}</span><strong class="kpi-value">${value}<em class="kpi-unit">${unit || ""}</em></strong><span class="kpi-note">${note || "Latest measured experiment"}</span></article>`; }

function lineChart(records, key) {
  const values = records.map((record) => Number(record[key])).filter((value) => Number.isFinite(value));
  if (!values.length) return emptyState("No measured history", "Run a workload to plot real PostgreSQL measurements.");
  const plotRecords = records.filter((record) => Number.isFinite(Number(record[key]))).slice(0, 30).reverse();
  const width = 720, height = 245, pad = { left: 38, right: 12, top: 16, bottom: 29 };
  const range = Math.max(...values) - Math.min(...values) || 1;
  const min = Math.min(...values) - range * .08, max = Math.max(...values) + range * .08;
  const x = (index) => pad.left + index * (width - pad.left - pad.right) / Math.max(plotRecords.length - 1, 1);
  const y = (value) => pad.top + (max - value) * (height - pad.top - pad.bottom) / (max - min);
  const points = plotRecords.map((record, index) => `${x(index)},${y(Number(record[key]))}`).join(" ");
  const area = `${pad.left},${height - pad.bottom} ${points} ${x(plotRecords.length - 1)},${height - pad.bottom}`;
  const labels = [max, min + (max - min) / 2, min];
  return `<div class="chart-wrap"><svg viewBox="0 0 ${width} ${height}" role="img" aria-label="${metricName(key)} across recent measured experiments">${labels.map((value) => `<line class="chart-grid" x1="${pad.left}" x2="${width - pad.right}" y1="${y(value)}" y2="${y(value)}"/><text class="chart-label" x="0" y="${y(value) + 3}">${number(value, 1)}</text>`).join("")}<polyline class="chart-line" points="${points}"/>${plotRecords.map((record, index) => `<circle class="chart-dot" cx="${x(index)}" cy="${y(Number(record[key]))}" r="3"><title>${dateTime(record.started_at)}: ${number(record[key])} ${metricUnit(key)}</title></circle>`).join("")}<text class="chart-label" x="${pad.left}" y="${height - 7}">Older</text><text class="chart-label" x="${width - 36}" y="${height - 7}">Latest</text></svg></div>`;
}

function metricComparison(validation) {
  if (!validation) return emptyState("No validation yet", "Run a real validation to compare model predictions with PostgreSQL measurements.");
  const metrics = Object.keys(validation.error_metrics || {}).filter((key) => validation.predicted_metrics?.[`predicted_${key}`] !== undefined && validation.actual_metrics?.[key] !== undefined);
  if (!metrics.length) return emptyState("No comparable metrics", "The selected validation does not contain both predicted and actual values.");
  return `<div class="comparison-list">${metrics.map((key) => `<div class="comparison"><div class="comparison-name">${metricName(key)}</div><div class="comparison-values"><div class="predicted-value"><span>PREDICTED</span><b>${number(validation.predicted_metrics[`predicted_${key}`])} ${metricUnit(key)}</b></div><div class="actual-value"><span>ACTUAL</span><b>${number(validation.actual_metrics[key])} ${metricUnit(key)}</b></div></div></div>`).join("")}</div>`;
}

function dashboard() {
  const latest = latestExperiment(); const validation = latestValidation(); const system = state.system || {};
  const metric = state.metric;
  const switches = [["average_latency_ms", "Avg latency"], ["p95_latency_ms", "P95"], ["actual_tps", "Throughput"], ["host_cpu_avg_percent", "CPU"]];
  return `${pageHero("Database performance workspace", "Measure workloads, estimate performance, and review the evidence before changing PostgreSQL.", `<button class="action-button" onclick="setPage('prediction')">Predict performance →</button>`)}
    <section class="status-grid"><article class="status-card"><div><span>DATABASE</span><strong>${escapeHtml(statusText(system.database))}</strong></div><i class="status-dot ${statusDot(system.database)}"></i></article><article class="status-card"><div><span>TELEMETRY</span><strong>${escapeHtml(statusText(system.telemetry))}</strong></div><i class="status-dot ${statusDot(system.telemetry)}"></i></article><article class="status-card"><div><span>ML MODELS</span><strong>${escapeHtml(statusText(system.ml_models))}</strong></div><i class="status-dot ${statusDot(system.ml_models)}"></i></article></section>
    <section class="kpi-grid">${kpi("Average latency", number(latest?.average_latency_ms), "ms")}${kpi("P95 latency", number(latest?.p95_latency_ms), "ms")}${kpi("Actual throughput", number(latest?.actual_tps), "TPS")}${kpi("Host CPU", number(latest?.host_cpu_avg_percent), "%")}${kpi("Lock waits", integer(latest?.lock_wait_count_max), "")}</section>
    <section class="two-col"><article class="card">${cardHead("Database performance", "Measurements from recent PostgreSQL workload experiments.", `<div class="metric-switch" role="group" aria-label="Select chart metric">${switches.map(([key, label]) => `<button class="${metric === key ? "active" : ""}" onclick="switchMetric('${key}')">${label}</button>`).join("")}</div>`)}${lineChart(state.experiments, metric)}</article><article class="card">${cardHead("Prediction accuracy", validation ? `Validation ${compact(validation.validation_id)} · ${validation.scenario}` : "A real validation compares predicted and measured performance.", `<button class="secondary-button" onclick="setPage('validation')">Open validation</button>`)}${metricComparison(validation)}</article></section>`;
}

function experimentsPage() {
  const rows = state.experiments;
  return `${pageHero("Experiment explorer", "Inspect real workload executions, telemetry coverage, and measured database performance.")}
  <article class="card">${cardHead("Measured experiments", `${rows.length} experiment${rows.length === 1 ? "" : "s"} available from PostgreSQL.`)}<div class="table-controls"><input id="experiment-search" class="field" type="search" placeholder="Search ID or scenario" aria-label="Search experiments" oninput="filterExperiments()"><select id="experiment-status" class="field" aria-label="Filter experiment status" onchange="filterExperiments()"><option value="">All statuses</option><option value="COMPLETED">Completed</option><option value="RUNNING">Running</option><option value="FAILED">Failed</option></select></div><div id="experiment-table">${experimentTable(rows)}</div></article>`;
}
function experimentTable(rows) {
  if (!rows.length) return emptyState("No experiments yet", "Run a banking workload to begin collecting performance intelligence.");
  return `<div class="data-table-wrap"><table class="data-table"><thead><tr><th>Experiment</th><th>Scenario</th><th>Concurrency</th><th>Target TPS</th><th>Actual TPS</th><th>Avg latency</th><th>P95</th><th>CPU</th><th>Status</th><th>Time</th></tr></thead><tbody>${rows.map((item) => `<tr class="data-row" tabindex="0" onclick="openExperiment('${item.experiment_id}')" onkeydown="if(event.key==='Enter')openExperiment('${item.experiment_id}')"><td class="mono strong">${compact(item.experiment_id)}</td><td>${statusBadge(item.scenario)}</td><td>${integer(item.configuration?.concurrency)}</td><td>${number(item.configuration?.target_tps)}</td><td>${number(item.actual_tps)}</td><td>${number(item.average_latency_ms)} ms</td><td>${number(item.p95_latency_ms)} ms</td><td>${number(item.host_cpu_avg_percent)}%</td><td>${statusBadge(item.status)}</td><td>${dateTime(item.started_at)}</td></tr>`).join("")}</tbody></table></div>`;
}
function filterExperiments() { const query = $("#experiment-search").value.toLowerCase(); const status = $("#experiment-status").value; const filtered = state.experiments.filter((item) => (!status || item.status === status) && `${item.experiment_id} ${item.scenario}`.toLowerCase().includes(query)); $("#experiment-table").innerHTML = experimentTable(filtered); }

function workloadFields(prefix, defaults = {}) { const scenarios = ["NORMAL_DAY", "SALARY_DAY", "MONTH_END", "FESTIVAL_SPIKE", "CARD_PAYMENT_SPIKE", "LOAN_PROCESSING", "HIGH_CONCURRENCY_TRANSFER"]; return `<div class="form-grid"><div class="form-field"><label for="${prefix}-scenario">Scenario</label><select class="field" id="${prefix}-scenario">${scenarios.map((item) => `<option value="${item}" ${item === (defaults.scenario || "NORMAL_DAY") ? "selected" : ""}>${item.replaceAll("_", " ")}</option>`).join("")}</select></div><div class="form-field"><label for="${prefix}-concurrency">Concurrency</label><input class="field" id="${prefix}-concurrency" type="number" min="1" value="${defaults.concurrency || 10}"></div><div class="form-field"><label for="${prefix}-tps">Target TPS</label><input class="field" id="${prefix}-tps" type="number" min="0.1" step="0.1" value="${defaults.target_tps || 10}"></div><div class="form-field"><label for="${prefix}-duration">Duration (seconds)</label><input class="field" id="${prefix}-duration" type="number" min="1" step="1" value="${defaults.duration_seconds || 10}"></div></div>`; }
function workloadFrom(prefix) { return { scenario: $(`#${prefix}-scenario`).value, concurrency: Number($(`#${prefix}-concurrency`).value), target_tps: Number($(`#${prefix}-tps`).value), duration_seconds: Number($(`#${prefix}-duration`).value) }; }
function predictionResults(result) { const metrics = Object.entries(result.predictions || {}); return `<div class="result-panel">${cardHead("Predicted performance", "Model-derived outputs. These values are not real measurements.")}<div class="result-grid">${metrics.map(([key, value]) => `<div class="metric-result"><span>PREDICTED ${metricName(key.replace("predicted_", ""))}</span><strong>${number(value)} <small>${metricUnit(key)}</small></strong></div>`).join("")}</div>${(result.warnings || []).map((warning) => `<div class="warning"><b>Coverage warning</b><span>${escapeHtml(warning)}</span></div>`).join("")}</div>`; }
function predictionPage() { return `${pageHero("Predict performance", "Configure a workload and estimate how PostgreSQL is expected to perform before running it.")}<section class="workbench"><div class="section-intro">${cardHead("Workload", "Inputs describe the workload sent to the trained performance model.")}</div><form id="prediction-form">${workloadFields("prediction")}<div class="form-actions"><button class="action-button" type="submit">Predict performance →</button><span class="form-note">Predictions are distinct from actual observations.</span></div></form><div id="prediction-result"></div></section>`; }
async function submitPrediction(event) { event.preventDefault(); const target = $("#prediction-result"); target.innerHTML = '<div class="skeleton" style="min-height:180px;margin-top:18px"></div>'; try { const result = await api("/api/predictions", { method: "POST", body: JSON.stringify(workloadFrom("prediction")) }); target.innerHTML = predictionResults(result); } catch (error) { target.innerHTML = `<div class="error-state" style="margin-top:18px"><div><b>Prediction unavailable</b><span>${escapeHtml(error.message)}</span></div></div>`; } }

function whatIfPage() { return `${pageHero("Compare workloads", "Compare how two workload configurations are predicted to perform without executing either against PostgreSQL.")}<section class="whatif-workspace"><div class="whatif-intro">${cardHead("Simulation", "Configure a baseline, then see what changes when workload intensity shifts.")}</div><form id="whatif-form"><div class="whatif-grid"><section class="whatif-config"><h3>Baseline</h3><p>Current workload configuration</p>${workloadFields("base", { concurrency: 10, target_tps: 10 })}</section><section class="whatif-config"><h3>What-if</h3><p>Alternative workload configuration</p>${workloadFields("changed", { concurrency: 20, target_tps: 10 })}</section></div><div class="whatif-action"><span class="form-note">Predictions only. No database workload is executed.</span><button class="action-button" type="submit">Compare predictions <span aria-hidden="true">→</span></button></div></form><div id="whatif-result"></div></section>`; }
function whatIfResults(result) { const entries = Object.entries(result.deltas || {}); return `<section class="whatif-results"><div class="results-heading"><div><h3>Prediction comparison</h3><p>Model-derived impact of the alternative workload.</p></div><strong>${escapeHtml(result.assessment || "Unavailable")}</strong></div><div class="delta-list">${entries.map(([key, value]) => `<div class="metric-delta"><div class="delta-name">${metricName(key.replace("predicted_", ""))}</div><div class="delta-values"><span>Baseline <b>${number(value.baseline)}</b></span><span class="delta-arrow" aria-hidden="true">→</span><span>What-if <b>${number(value.modified)}</b></span></div><div class="delta-change">${value.percentage_change === null ? "Percentage change unavailable" : `${value.percentage_change >= 0 ? "+" : ""}${number(value.percentage_change)}%`} · ${value.absolute_change >= 0 ? "+" : ""}${number(value.absolute_change)}</div></div>`).join("")}</div>${(result.warnings || []).map((warning) => `<div class="warning"><b>Coverage note</b><span>${escapeHtml(warning)}</span></div>`).join("")}</section>`; }
async function submitWhatIf(event) { event.preventDefault(); const target = $("#whatif-result"); target.innerHTML = '<div class="skeleton" style="min-height:190px;margin-top:18px"></div>'; try { const result = await api("/api/what-if", { method: "POST", body: JSON.stringify({ baseline: workloadFrom("base"), modified: workloadFrom("changed") }) }); target.innerHTML = whatIfResults(result); } catch (error) { target.innerHTML = `<div class="error-state" style="margin-top:18px"><div><b>What-if analysis unavailable</b><span>${escapeHtml(error.message)}</span></div></div>`; } }

function optimizationPage() { const latest = latestExperiment(); return `${pageHero("Performance assessment", "Evidence-based advisory recommendations from a measured experiment.")}<article class="card">${cardHead("Select measured experiment", "FinTwin does not apply database changes automatically.")}<div class="table-controls"><select id="optimization-experiment" class="field" aria-label="Experiment for optimization analysis">${state.experiments.map((item) => `<option value="${item.experiment_id}" ${item.experiment_id === latest?.experiment_id ? "selected" : ""}>${compact(item.experiment_id)} · ${item.scenario} · ${dateTime(item.started_at)}</option>`).join("")}</select><button class="action-button" onclick="loadOptimization()" ${state.experiments.length ? "" : "disabled"}>Analyze performance</button></div><div id="optimization-result">${state.experiments.length ? '<p class="form-note">Choose an experiment to retrieve its live evidence and advisory recommendations.</p>' : emptyState("No experiment available", "Run a real workload before generating optimization advice.")}</div></article>`; }
function recommendationPanel(data) { if (!data.recommendations?.length) return `<div class="empty-state"><div><b>${escapeHtml(data.overall_status || "NORMAL")}</b><span>${escapeHtml(data.summary || "No significant bottlenecks were detected.")}</span></div></div>`; return `<div class="result-panel">${cardHead("Recommended actions", `${data.recommendations.length} advisory recommendation${data.recommendations.length === 1 ? "" : "s"}.`)}${data.recommendations.map((item) => `<details class="recommendation"><summary><div><span class="badge ${item.severity === "HIGH" ? "elevated" : ""}">${escapeHtml(item.severity)} PRIORITY</span><h4>${escapeHtml(item.title)}</h4></div><span>⌄</span></summary><div class="recommendation-content"><div><strong>WHY</strong><p>${escapeHtml(item.description)}</p></div><div><strong>EVIDENCE</strong><p class="mono">${escapeHtml(JSON.stringify(item.evidence))}</p></div><div><strong>RECOMMENDED ACTION</strong><p>${escapeHtml(item.recommended_action)}</p></div><div><strong>VALIDATION</strong><p>${item.requires_validation ? "Validation required before applying any change." : "No automatic change is performed."}</p></div></div></details>`).join("")}${(data.warnings || []).map((warning) => `<div class="warning"><b>Availability note</b><span>${escapeHtml(warning)}</span></div>`).join("")}</div>`; }
async function loadOptimization() { const target = $("#optimization-result"), id = $("#optimization-experiment").value; target.innerHTML = '<div class="skeleton" style="min-height:200px;margin-top:18px"></div>'; try { target.innerHTML = recommendationPanel(await api(`/api/recommendations/${id}`)); } catch (error) { target.innerHTML = `<div class="error-state" style="margin-top:18px"><div><b>Analysis unavailable</b><span>${escapeHtml(error.message)}</span></div></div>`; } }

function validationPage() { const summary = state.validationSummary || {}; const overall = summary.overall || {}; const latest = latestValidation(); const avgError = overall.average_latency_ms?.mape; const best = Object.entries(overall).filter(([, value]) => value.mape !== null && value.mape !== undefined).sort((a, b) => a[1].mape - b[1].mape)[0]; return `${pageHero("Does FinTwin predict reality?", "Every comparison below pairs model output with a real PostgreSQL workload execution.", `<button class="action-button" onclick="showValidationRun()">Run real validation</button>`)}<section class="kpi-grid" style="grid-template-columns:repeat(3,1fr)">${kpi("Validation experiments", integer(summary.validation_count), "", "Completed predicted-vs-actual comparisons")}${kpi("Avg latency error", avgError === undefined ? "—" : number(avgError), avgError === undefined ? "" : "%", "MAPE across completed validations")}${kpi("Best prediction target", best ? metricName(best[0]) : "—", "", best ? `${number(best[1].mape)}% MAPE` : "More real validations required")}</section><article class="card" id="validation-run-panel">${cardHead("Run a real validation", "This action predicts, executes the same workload against PostgreSQL, captures telemetry, and stores the comparison.")}<form id="validation-run-form">${workloadFields("validation-run")}<div class="form-actions"><button class="action-button" type="submit">Execute real validation</button><span class="form-note">This creates a real PostgreSQL experiment and may take the selected duration to complete.</span></div></form><div id="validation-run-result"></div></article><section class="two-col"><article class="card">${cardHead("Predicted vs actual", latest ? `Validation ${compact(latest.validation_id)} · ${latest.scenario}` : "No completed validation available.")}${metricComparison(latest)}</article><article class="card">${cardHead("Error distribution", "Absolute percentage errors from completed real validations.")} ${validationErrorList()}</article></section><article class="card">${cardHead("Validation records", "Each row is a persisted prediction-to-experiment match.")} ${validationTable()}</article>`; }
function validationErrorList() { const list = state.validations.filter((item) => item.validation_status === "COMPLETED"); if (!list.length) return emptyState("No validation history", "Execute a real validation to begin measuring model error."); return `<div class="comparison-list">${list.slice(0, 6).map((item) => { const metrics = Object.entries(item.error_metrics || {}).filter(([, value]) => value.percentage_error !== null && value.percentage_error !== undefined); const average = metrics.length ? metrics.reduce((sum, [, value]) => sum + Number(value.percentage_error), 0) / metrics.length : null; return `<div class="comparison"><div class="comparison-name">${escapeHtml(item.scenario)} · ${compact(item.validation_id)}</div><div class="comparison-values"><div><span>AVG. AVAILABLE ERROR</span><b>${average === null ? "—" : `${number(average)}%`}</b></div><div><span>STATUS</span><b>${escapeHtml(item.validation_status)}</b></div></div></div>`; }).join("")}</div>`; }
function validationTable() { if (!state.validations.length) return emptyState("No validations yet", "Run a prediction against a real workload to create the first record."); return `<div class="data-table-wrap"><table class="data-table"><thead><tr><th>Validation</th><th>Scenario</th><th>Actual experiment</th><th>Status</th><th>Created</th></tr></thead><tbody>${state.validations.map((item) => `<tr><td class="mono strong">${compact(item.validation_id)}</td><td>${statusBadge(item.scenario)}</td><td class="mono">${compact(item.actual_experiment_id)}</td><td>${statusBadge(item.validation_status)}</td><td>${dateTime(item.created_at)}</td></tr>`).join("")}</tbody></table></div>`; }
function showValidationRun() { $("#validation-run-panel")?.scrollIntoView({ behavior: "smooth", block: "center" }); $("#validation-run-scenario")?.focus(); }
async function submitValidation(event) { event.preventDefault(); const target = $("#validation-run-result"); const button = $("#validation-run-form button[type='submit']"); button.disabled = true; button.textContent = "Running real validation…"; target.innerHTML = '<div class="skeleton" style="min-height:130px;margin-top:18px"></div>'; try { const result = await api("/api/validation", { method: "POST", body: JSON.stringify(workloadFrom("validation-run")) }); if (result.validation_status !== "COMPLETED") throw new Error(result.error_message || "Validation did not complete."); target.innerHTML = `<div class="warning" style="border-color:rgba(84,209,189,.28);background:rgba(84,209,189,.08);color:#c9fff5"><b>Validation completed</b><span>Real PostgreSQL experiment ${escapeHtml(compact(result.actual_experiment_id))} has been matched to prediction ${escapeHtml(compact(result.prediction_id))}. Refreshing results…</span></div>`; await refreshData(); setPage("validation"); toast("Real validation completed."); } catch (error) { target.innerHTML = `<div class="error-state" style="margin-top:18px"><div><b>Validation unavailable</b><span>${escapeHtml(error.message)}</span></div></div>`; button.disabled = false; button.textContent = "Execute real validation"; } }

function render() { if (state.loading) return skeleton(); if (state.error) { app.innerHTML = errorState("Database connection unavailable", state.error); return; } const views = { dashboard, experiments: experimentsPage, prediction: predictionPage, whatif: whatIfPage, optimization: optimizationPage, validation: validationPage }; app.innerHTML = views[state.page](); if (state.page === "prediction") $("#prediction-form").addEventListener("submit", submitPrediction); if (state.page === "whatif") $("#whatif-form").addEventListener("submit", submitWhatIf); if (state.page === "validation") $("#validation-run-form").addEventListener("submit", submitValidation); }

async function refreshData(showToast = false) {
  state.loading = true; state.error = null; render();
  try {
    const [health, system, experiments, validations, validationSummary] = await Promise.all([api("/api/health"), api("/api/system/status"), api("/api/experiments"), api("/api/validation"), api("/api/validation/summary")]);
    Object.assign(state, { health, system, experiments, validations, validationSummary, loading: false }); setSystemStatus(); render(); if (showToast) toast("Live data refreshed.");
  } catch (error) { state.loading = false; state.error = error.message; state.system = { database: "offline", telemetry: "unavailable", ml_models: "unavailable" }; setSystemStatus(); render(); if (showToast) toast("Refresh failed: " + error.message, true); }
}
function toast(message, isError = false) { const element = document.createElement("div"); element.className = `toast${isError ? " error" : ""}`; element.textContent = message; $("#toast-region").append(element); setTimeout(() => element.remove(), 3500); }
async function openExperiment(id) { const drawer = $("#drawer"), backdrop = $("#drawer-backdrop"); drawer.inert = false; drawer.innerHTML = '<div class="skeleton" style="min-height:270px"></div>'; drawer.classList.add("open"); backdrop.classList.add("open"); drawer.setAttribute("aria-hidden", "false"); try { const data = await api(`/api/experiments/${id}`); const e = data.experiment; const config = e.configuration || {}; drawer.innerHTML = `<button class="icon-button drawer-close" aria-label="Close detail" onclick="closeDrawer()">×</button><p class="eyebrow">MEASURED EXPERIMENT</p><h2>${escapeHtml(e.scenario)}</h2><p class="mono" style="color:var(--muted)">${escapeHtml(e.experiment_id)}</p><div class="drawer-section"><h3>Performance</h3><div class="key-list"><div><span>Actual TPS</span><b>${number(e.actual_tps)}</b></div><div><span>Avg latency</span><b>${number(e.average_latency_ms)} ms</b></div><div><span>P95 latency</span><b>${number(e.p95_latency_ms)} ms</b></div><div><span>Host CPU</span><b>${number(e.host_cpu_avg_percent)}%</b></div></div></div><div class="drawer-section"><h3>Workload configuration</h3><div class="key-list"><div><span>Concurrency</span><b>${integer(config.concurrency)}</b></div><div><span>Target TPS</span><b>${number(config.target_tps)}</b></div><div><span>Duration</span><b>${number(config.duration_seconds)} s</b></div><div><span>Telemetry samples</span><b>${integer(e.telemetry_sample_count)}</b></div></div></div><div class="drawer-section"><h3>Telemetry</h3>${data.telemetry.length ? `<div class="key-list"><div><span>Latest CPU</span><b>${number(data.telemetry[0].host_cpu_percent)}%</b></div><div><span>Latest memory</span><b>${number(data.telemetry[0].host_memory_percent)}%</b></div><div><span>Latest lock waits</span><b>${integer(data.telemetry[0].lock_wait_count)}</b></div><div><span>Blocked sessions</span><b>${integer(data.telemetry[0].blocked_sessions)}</b></div></div>` : emptyState("Telemetry unavailable", "No telemetry sample is stored for this experiment.")}</div><div class="drawer-section"><h3>Validation</h3>${data.validations.length ? `<p class="form-note">${data.validations.length} validation record(s) linked to this actual experiment.</p>` : '<p class="form-note">No predicted-vs-actual validation is linked to this experiment.</p>'}</div>`; } catch (error) { drawer.innerHTML = `<button class="icon-button drawer-close" aria-label="Close detail" onclick="closeDrawer()">×</button>${errorState("Experiment unavailable", error.message)}`; } }
function closeDrawer() { $("#drawer").classList.remove("open"); $("#drawer-backdrop").classList.remove("open"); $("#drawer").setAttribute("aria-hidden", "true"); $("#drawer").inert = true; }
function switchMetric(metric) { state.metric = metric; render(); }

window.setPage = setPage; window.switchMetric = switchMetric; window.filterExperiments = filterExperiments; window.openExperiment = openExperiment; window.closeDrawer = closeDrawer; window.loadOptimization = loadOptimization; window.showValidationRun = showValidationRun; window.toggleTheme = toggleTheme;
applyTheme(state.theme);
document.querySelectorAll(".nav-item").forEach((button) => button.addEventListener("click", () => setPage(button.dataset.page)));
$("#theme-toggle").addEventListener("click", toggleTheme);
$("#refresh-button").addEventListener("click", () => refreshData(true)); $("#drawer-backdrop").addEventListener("click", closeDrawer);
refreshData();
