CREATE TABLE IF NOT EXISTS branches (
    branch_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_name VARCHAR(120) NOT NULL,
    branch_code VARCHAR(20) NOT NULL UNIQUE,
    address VARCHAR(255) NOT NULL,
    city VARCHAR(80) NOT NULL,
    state VARCHAR(80) NOT NULL,
    ifsc_code VARCHAR(20) NOT NULL UNIQUE,
    phone VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT branches_branch_code_ck CHECK (branch_code <> ''),
    CONSTRAINT branches_ifsc_code_ck CHECK (ifsc_code <> '')
);

CREATE TABLE IF NOT EXISTS customers (
    customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(160) NOT NULL,
    date_of_birth DATE NOT NULL,
    gender VARCHAR(20) NOT NULL CHECK (gender IN ('FEMALE', 'MALE', 'NON_BINARY', 'UNSPECIFIED')),
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(20) NOT NULL UNIQUE,
    address VARCHAR(255) NOT NULL,
    city VARCHAR(80) NOT NULL,
    state VARCHAR(80) NOT NULL,
    kyc_status VARCHAR(20) NOT NULL CHECK (kyc_status IN ('PENDING', 'VERIFIED', 'REJECTED')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    branch_id BIGINT NOT NULL REFERENCES branches(branch_id)
);

CREATE TABLE IF NOT EXISTS accounts (
    account_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES customers(customer_id),
    branch_id BIGINT NOT NULL REFERENCES branches(branch_id),
    account_number VARCHAR(24) NOT NULL UNIQUE,
    account_type VARCHAR(20) NOT NULL CHECK (account_type IN ('SAVINGS', 'CURRENT')),
    balance NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (balance >= 0),
    currency CHAR(3) NOT NULL DEFAULT 'INR' CHECK (currency = 'INR'),
    open_date DATE NOT NULL,
    closed_date DATE,
    status VARCHAR(20) NOT NULL CHECK (status IN ('ACTIVE', 'INACTIVE', 'CLOSED')),
    CONSTRAINT accounts_closed_date_ck CHECK (closed_date IS NULL OR closed_date >= open_date),
    CONSTRAINT accounts_status_date_ck CHECK ((status = 'CLOSED' AND closed_date IS NOT NULL) OR status <> 'CLOSED')
);

CREATE TABLE IF NOT EXISTS merchants (
    merchant_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(160) NOT NULL,
    category VARCHAR(80) NOT NULL,
    mcc_code VARCHAR(4) NOT NULL,
    city VARCHAR(80) NOT NULL,
    state VARCHAR(80) NOT NULL,
    country CHAR(2) NOT NULL DEFAULT 'IN',
    is_online BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(20) NOT NULL CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE IF NOT EXISTS transactions (
    transaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_account_id BIGINT REFERENCES accounts(account_id),
    to_account_id BIGINT REFERENCES accounts(account_id),
    merchant_id BIGINT REFERENCES merchants(merchant_id),
    transaction_time TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    amount NUMERIC(18, 2) NOT NULL CHECK (amount > 0),
    currency CHAR(3) NOT NULL DEFAULT 'INR' CHECK (currency = 'INR'),
    transaction_type VARCHAR(20) NOT NULL CHECK (transaction_type IN ('TRANSFER', 'DEPOSIT', 'WITHDRAWAL', 'PAYMENT')),
    description VARCHAR(255),
    reference_id VARCHAR(64) NOT NULL UNIQUE,
    channel VARCHAR(20) NOT NULL CHECK (channel IN ('BRANCH', 'ATM', 'ONLINE', 'MOBILE', 'POS')),
    status VARCHAR(20) NOT NULL CHECK (status IN ('SUCCESS', 'FAILED', 'PENDING')),
    CONSTRAINT transactions_distinct_accounts_ck CHECK (from_account_id IS NULL OR to_account_id IS NULL OR from_account_id <> to_account_id),
    CONSTRAINT transactions_shape_ck CHECK (
        (transaction_type = 'TRANSFER' AND from_account_id IS NOT NULL AND to_account_id IS NOT NULL) OR
        (transaction_type = 'DEPOSIT' AND to_account_id IS NOT NULL) OR
        (transaction_type = 'WITHDRAWAL' AND from_account_id IS NOT NULL) OR
        (transaction_type = 'PAYMENT' AND from_account_id IS NOT NULL AND merchant_id IS NOT NULL)
    )
);

CREATE TABLE IF NOT EXISTS loans (
    loan_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES customers(customer_id),
    account_id BIGINT NOT NULL REFERENCES accounts(account_id),
    branch_id BIGINT NOT NULL REFERENCES branches(branch_id),
    loan_type VARCHAR(30) NOT NULL CHECK (loan_type IN ('PERSONAL', 'HOME', 'EDUCATION', 'VEHICLE')),
    principal_amount NUMERIC(18, 2) NOT NULL CHECK (principal_amount > 0),
    interest_rate NUMERIC(7, 4) NOT NULL CHECK (interest_rate >= 0),
    tenure_months INTEGER NOT NULL CHECK (tenure_months > 0),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('ACTIVE', 'CLOSED', 'DEFAULTED')),
    CONSTRAINT loans_dates_ck CHECK (end_date > start_date)
);

CREATE INDEX IF NOT EXISTS idx_accounts_customer_id ON accounts(customer_id);
CREATE INDEX IF NOT EXISTS idx_accounts_branch_id ON accounts(branch_id);
CREATE INDEX IF NOT EXISTS idx_transactions_from_account_id ON transactions(from_account_id);
CREATE INDEX IF NOT EXISTS idx_transactions_to_account_id ON transactions(to_account_id);
CREATE INDEX IF NOT EXISTS idx_transactions_transaction_time ON transactions(transaction_time);
CREATE INDEX IF NOT EXISTS idx_transactions_merchant_id ON transactions(merchant_id);
CREATE INDEX IF NOT EXISTS idx_loans_customer_id ON loans(customer_id);
CREATE INDEX IF NOT EXISTS idx_loans_account_id ON loans(account_id);
CREATE INDEX IF NOT EXISTS idx_loans_branch_id ON loans(branch_id);

CREATE TABLE IF NOT EXISTS experiment_runs (
    experiment_id UUID PRIMARY KEY,
    scenario VARCHAR(40) NOT NULL,
    configuration JSONB NOT NULL,
    started_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ,
    status VARCHAR(20) NOT NULL CHECK (status IN ('RUNNING', 'COMPLETED', 'FAILED')),
    requested_operations INTEGER NOT NULL DEFAULT 0 CHECK (requested_operations >= 0),
    completed_operations INTEGER NOT NULL DEFAULT 0 CHECK (completed_operations >= 0),
    successful_operations INTEGER NOT NULL DEFAULT 0 CHECK (successful_operations >= 0),
    failed_operations INTEGER NOT NULL DEFAULT 0 CHECK (failed_operations >= 0),
    actual_tps NUMERIC(18, 4),
    average_latency_ms NUMERIC(18, 4),
    p50_latency_ms NUMERIC(18, 4), p95_latency_ms NUMERIC(18, 4), p99_latency_ms NUMERIC(18, 4), error_rate NUMERIC(10,6)
);

ALTER TABLE experiment_runs ADD COLUMN IF NOT EXISTS p50_latency_ms NUMERIC(18,4);
ALTER TABLE experiment_runs ADD COLUMN IF NOT EXISTS p95_latency_ms NUMERIC(18,4);
ALTER TABLE experiment_runs ADD COLUMN IF NOT EXISTS p99_latency_ms NUMERIC(18,4);
ALTER TABLE experiment_runs ADD COLUMN IF NOT EXISTS error_rate NUMERIC(10,6);

CREATE TABLE IF NOT EXISTS workload_events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    experiment_id UUID NOT NULL REFERENCES experiment_runs(experiment_id) ON DELETE CASCADE,
    operation VARCHAR(40) NOT NULL,
    latency_ms NUMERIC(18, 4) NOT NULL CHECK (latency_ms >= 0),
    success BOOLEAN NOT NULL,
    error_message TEXT,
    recorded_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_workload_events_experiment_id ON workload_events(experiment_id);
CREATE INDEX IF NOT EXISTS idx_workload_events_recorded_at ON workload_events(recorded_at);

CREATE TABLE IF NOT EXISTS telemetry_samples (
    telemetry_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    experiment_id UUID NOT NULL REFERENCES experiment_runs(experiment_id) ON DELETE CASCADE,
    sample_kind VARCHAR(10) NOT NULL CHECK (sample_kind IN ('INITIAL','SAMPLE','FINAL')),
    captured_at TIMESTAMPTZ NOT NULL, active_connections INTEGER, idle_connections INTEGER,
    waiting_connections INTEGER, max_connections INTEGER, xact_commit BIGINT, xact_rollback BIGINT,
    blks_read BIGINT, blks_hit BIGINT, tup_inserted BIGINT, tup_updated BIGINT, tup_deleted BIGINT,
    deadlocks BIGINT, lock_count BIGINT, lock_wait_count BIGINT, blocked_sessions INTEGER,
    database_size_bytes BIGINT, cache_hit_ratio NUMERIC(10,4), host_cpu_percent NUMERIC(10,4), host_memory_percent NUMERIC(10,4)
);
CREATE INDEX IF NOT EXISTS idx_telemetry_samples_experiment_time ON telemetry_samples(experiment_id, captured_at);

CREATE TABLE IF NOT EXISTS experiment_summaries (
    experiment_id UUID PRIMARY KEY REFERENCES experiment_runs(experiment_id) ON DELETE CASCADE,
    error_rate NUMERIC(10,6), p50_latency_ms NUMERIC(18,4), p95_latency_ms NUMERIC(18,4), p99_latency_ms NUMERIC(18,4),
    active_connections_max INTEGER, blocked_sessions_max INTEGER, lock_wait_count_max BIGINT,
    db_xact_commit_delta BIGINT, db_xact_rollback_delta BIGINT, db_deadlocks_delta BIGINT, db_cache_hit_ratio NUMERIC(10,4),
    host_cpu_avg_percent NUMERIC(10,4), host_memory_avg_percent NUMERIC(10,4), db_size_before_bytes BIGINT, db_size_after_bytes BIGINT,
    telemetry_sample_count INTEGER NOT NULL DEFAULT 0, telemetry_error_count INTEGER NOT NULL DEFAULT 0, generated_at TIMESTAMPTZ NOT NULL
);
